# Generated by Django 4.2.6 on 2024-02-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'Категория Новости', 'verbose_name_plural': 'Категории Новостей'},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': 'Категория Поста', 'verbose_name_plural': 'Категории Постов'},
        ),
    ]
