# Generated by Django 4.2.6 on 2024-02-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Бренд')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Слаг Бренда')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель автомобиля')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Слаг модели')),
                ('image', models.ImageField(default=None, upload_to='cars_catalog', verbose_name='Изображение автомобиля')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
            ],
        ),
    ]
