# Generated by Django 4.2.6 on 2024-02-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='cars_catalog', verbose_name='Изображение автомобиля'),
        ),
    ]
